name: Build and Release (Windows)

on:
  push:

jobs:
  build-capacitor:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-versions: ["16.13.1"]

    steps:
      - uses: actions/checkout@v2

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Setup NodeJS Environment ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install && yarn add @quasar/cli
      - run: ./node_modules/@quasar/app/bin/quasar build -m electron -P always

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/electron/Packaged/paperlib Setup ${{ steps.version.outputs.content }}.exe
            ./dist/electron/Packaged/latest.yml
          draft: true
          tag_name: v${{ steps.version.outputs.content }}-win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}